name: Autobot
# only run if .md updated
on: push
jobs:
  updateautobot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
         run: | rev "$SUPER_SECRET"
    - name: AutoBotYamlFileSetter
      uses: nickssmith/AutoBotYaml@0.7.2
      with:
        token: ${{ secrets.SFLOrgReadAccessToken }}
    
