name: MD to PDF
on: push
jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Markdown to PDF
      uses: valtyr/pandoc-action@v0.1-alpha
    - name: echo
      run: echo "hello world"
    - name: ls
      run: ls
    - name: gs
      run: git status
    - name: git add
      run: find . -name '*.pdf' -print0 | xargs -0 git add
    - name: gs
      run: git status
    - name: commit
      run: git config --global user.email "nsmith@sflscientific.com" && git config --global user.name "Nick" && git commit -m 'added pdfs'
    - name: push
      run: git push
    - name: Push to branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'master-built'
        commit_message: 'Build master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: PR with convreted to PDF
        committer: Nick Smith <nickssmith@users.noreply.github.com>
        title: File conversions
        body: This is an auto-generated PR
        labels: pdfs, automated pr
        branch: md-to-pdf-patches
