name: MD to PDF
on: push
jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Markdown to PDF
      uses: valtyr/pandoc-action@v0.1-alpha
    - name: Commit pdf to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
            # Required
            commit_message: Apply automatic changes

            # Optional options appended to `git-commit`
            commit_options: '--no-verify --signoff'

            # Optional glob pattern of files which should be added to the commit
            file_pattern: *.pdf

            # Optional local file path to the repository
            repository: .

            # Optional commit user and author settings
            commit_user_name: My GitHub Actions Bot
            commit_user_email: my-github-actions-bot@example.org
            commit_author: Author <actions@github.com>

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: PR with convreted to PDF
        committer: Nick Smith <nickssmith@users.noreply.github.com>
        title: File conversions
        body: This is an auto-generated PR
        labels: pdfs, automated pr
        branch: md-to-pdf-patches
