name: README to PDF
on: push
jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Markdown to PDF
      uses: valtyr/pandoc-action@v0.1-alpha
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: .
