name: Check Spelling
# https://github.com/marketplace/actions/check-spelling-js-vue-html-markdown-text
# for conifg
# make this a required check for merge
on:
  push:
    paths:
      - '**.txt'
      - '**.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@master
