name: Argument tense check
on:
  push:
    paths:
      - '**.py'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check args are present tense
      uses: nickssmith/PresentTenseArgs@0.2

    
