name: TODO and comment check
# https://github.com/marketplace/actions/check-spelling-js-vue-html-markdown-text
# for conifg
# make this a required check for merge
on: push
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: TODO and commented out code checker
      uses: nickssmith/TODO_and_CommentedCode_Check@1.0
    
